version: "3.1"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.1.1}
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - xpack.monitoring.collection.enabled=true
#      - xpack.license.self_generated.type=basic/trial
      - xpack.security.enabled=true
      - cluster.name=DevCluster
      - node.name=elasticsearch
      - discovery.type=single-node
      - network.host=0.0.0.0
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-7.1.1}
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    networks:
      - elastic
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"

networks:
  elastic: