name: Build rPi project

on:
  push:

jobs:
  build-rpi-project:
    runs-on: azul/zulu-openjdk-alpine:17
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build