name: Build rPi project

on:
  push:

jobs:
  build-rpi-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run build with Docker Compose
        run: ./docker/dc build
